name: ADF Dev pipeline

on:
  push:
    branches:
      - dev

run-name: ${{ inputs.Platform }} Build-${{ github.run_number }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 3
    
    - name: Fetch all history for all branches
      run: git log --oneline --all

    - name: Identify changed folders under 'FIG'
      run: |
        # Get the list of folders that have changed in the 'FIG' directory
        CHANGED_FOLDERS=$(git diff --name-only HEAD HEAD~1 |  grep 'Azure Data Factory/FIG/' | cut -d '/' -f3 | sort | uniq)
        echo "Changed Folders:"
        echo "$CHANGED_FOLDERS"
