name: ADF Dev pipeline

on:
  push:
    branches:
      - dev

run-name: ${{ inputs.Platform }} ADF Release-${{ github.run_number }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Files
      run: git log --oneline --all --no-pager
