name: ADF Release pipeline

on:
  workflow_dispatch:
    inputs:
      DEV:
        type: boolean
        description: Dev
        default: true
      UAT:
        type: boolean
        description: UAT
        default: true
      PROD:
        type: boolean
        description: PROD
        default: true
      build_artifact:
        description: 'Build Artifact'
        required: false
        type: string

run-name: ADF Release

permissions:
  id-token: write
  contents: read
  
jobs:
  Deploy-ADF-Dev:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  Deploy-ADF-UAT:
    runs-on: ubuntu-latest
    environment: UAT

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  Deploy-ADF-Prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


           
