name: ADF Release pipeline

on: 
  push:
    branches:
    - pwsh-test

  
jobs:
  Deploy-ADF-Dev:
    runs-on: Windows

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Copy Files
      run: |
          $User = "userdev"
          $PWord = ConvertTo-SecureString -String "P@sswOrd1234" -AsPlainText -Force
          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
          New-PSDrive -Name "Z" -PSProvider "FileSystem"  -root "\\devcomp01" -credential $Credential -Persist
          $src = 'pwsh'
          $dst = 'Z:C$\Scripts\Portfolio'
          robocopy $src $dst .
          Remove-PSDrive -Name "Z"
