name: ADF Release pipeline

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Platform'
        required: true
        type: choice
        options:
          - Apterra
          - Aqua
          - Eliant
          - Foundation Home Loans
          - HaydockFinance
          - HR Data
          - Liquidity Matrix
          - MidCap
          - NewFi
          - Petros
          - PK Air
          - Redding Ridge
          - Reference
          - SolidBriq
          - Spreads
          - Wheels
      DEV:
        type: boolean
        description: DEV
        default: true
      UAT:
        type: boolean
        description: UAT
        default: true
      PROD:
        type: boolean
        description: PROD
        default: true
      build_artifact:
        description: 'Build Artifact'
        required: false
        type: string

run-name: ${{ inputs.Platform }} ADF Release-${{ github.run_number }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build 
      uses: actions/upload-artifact@v4
      with:
          name: build-${{ github.run_number }}
          path: |
            .parameters
            test.sh

    # - name: Download Artifact
    #   if: ${{ inputs.build_artifact != '' }}
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: ${{ inputs.build_artifact }}
    #     # run-id::
    #     # github-token:
    

  DEV:
    runs-on: ubuntu-latest
    if:  ${{ inputs.DEV }} 
    environment: DEV
    needs: [Build]

    steps:

    - run: echo "Pass"

  UAT:
    runs-on: ubuntu-latest
    environment: UAT
    if:  ${{ inputs.UAT &&  always() }}
    needs: [DEV]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ github.run_number }}

    - run: error

  PROD:
    runs-on: ubuntu-latest
    if:  ${{ inputs.PROD && !failure() && always()  }} 
    environment: prod
    needs: [DEV, UAT]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ github.run_number }}

    - run: cat test.sh


           
