name: ADF Release pipeline

on: 
  push:
    branches:
    - main
run-name: Deploy to ${{ inputs.Environment }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Deploy-ADF-Dev:
    runs-on: windows-latest
    environment: ${{ inputs.Environment }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Delete unwanted integration runtime
      run: |
          robocopy
