name: ADF Release pipeline

on:
  workflow_dispatch:
    inputs:
      DEV:
        type: boolean
        description: DEV
        default: true
      UAT:
        type: boolean
        description: UAT
        default: true
      PROD:
        type: boolean
        description: PROD
        default: true
      build_artifact:
        description: 'Build Artifact'
        required: false
        type: string

run-name: ADF Release-$GITHUB_RUN_NUMBER

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build 
      uses: actions/upload-artifact@v4
      with:
          name: build-${{ github.run_number }}
          path: |
            .parameters
            test.sh

  DEV:
    runs-on: ubuntu-latest
    if:  ${{ inputs.DEV }} 
    environment: DEV
    needs: [Build]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-$GITHUB_RUN_NUMBER

    - run: cat test.sh

  UAT:
    runs-on: ubuntu-latest
    environment: UAT
    if:  ${{ inputs.UAT &&  always() }}
    needs: [DEV]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-$GITHUB_RUN_NUMBER

    - run: cat test.sh

  PROD:
    runs-on: ubuntu-latest
    if:  ${{ inputs.PROD &&  always() }}
    environment: prod
    needs: [DEV, UAT]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-$GITHUB_RUN_NUMBER

    - run: cat test.sh


           
