name: ADF Release pipeline

on: 
  push:
    branches:
    - main
run-name: Deploy to ${{ inputs.Environment }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Deploy-ADF-Dev:
    runs-on: windows-latest
    environment: ${{ inputs.Environment }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Delete unwanted integration runtime
      run: |
          $User = "rahul"
          $PWord = ConvertTo-SecureString -String "Admin@123hello" -AsPlainText -Force
          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
          New-PSDrive -Name "N" -PSProvider "FileSystem"  -root "\\135.237.96.171\Actions" -credential $Credential
          $src = 'c:\data'
          $dst = 'n:\data'
          robocopy $src $dst test.sh 
          Remove-PSDrive -Name "N"
