name: ADF Release pipeline

on:
  workflow_dispatch:
    inputs:
      DEV:
        type: boolean
        description: Dev
        default: true
      UAT:
        type: boolean
        description: UAT
        default: true
      PROD:
        type: boolean
        description: PROD
        default: true
      build_artifact:
        description: 'Build Artifact'
        required: false
        type: string

run-name: ADF Release

permissions:
  id-token: write
  contents: read
  
jobs:
  Deploy-ADF-Dev:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
          
    - name: Install Datafactory Az tools
      run: |
          Install-Module Az.Resources -Force -AllowClobber
          Install-Module Az.DataFactory -MinimumVersion "1.10.0" -Force -AllowClobber


           
