name: ADF Release pipeline

on:
  workflow_dispatch:
    inputs:
      DEV:
        type: boolean
        description: DEV
        default: true
      UAT:
        type: boolean
        description: UAT
        default: true
      PROD:
        type: boolean
        description: PROD
        default: true
      build_artifact:
        description: 'Build Artifact'
        required: false
        type: string

run-name: ADF Release

permissions:
  id-token: write
  contents: read
  
jobs:
  Dev:
    runs-on: ubuntu-latest
    if:  ${{ inputs.DEV }} 
    environment: DEV

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  UAT:
    runs-on: ubuntu-latest
    environment: UAT
    if:  ${{ always() }}
    needs: [Dev]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  PROD:
    runs-on: ubuntu-latest
    if:  ${{ inputs.PROD &&  always() }}
    environment: prod
    needs: [Dev, UAT]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


           
