name: Demo pipeline

on:
  push:
    branches:
      - dev

run-name: Demo

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build 
      uses: actions/upload-artifact@v4
      with:
          name: build-${{ github.run_number }}
          path: |
            .parameters
            test.sh

           
