name: Copy Release pipeline

on: 
  push:
    branches:
    - pwsh-test

jobs:
  Deploy-ADF-Dev:
    runs-on: Windows
    # environment: prod

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Copy Files to Windows Backup
      uses: ./.github/copy-files-windows
      with:
        Source: '\\machine_web_1\C$\Apache24\conf\httpd.conf'
        Machines: 'machine_web_1'
        Admin_Login: 'userdev'
        Password: 'P@ssw0rd1234'
        Destination_Folder: 'C:/Apache24\config-backup\${{ github.run_number }}'

    - name: Copy conf to Web 1
      uses: ./.github/copy-files-windows
      with:
        Source: 'uat'
        Machines: 'machine_web_1'
        Admin_Login: 'userdev'
        Password: 'P@ssw0rd1234'
        Destination_Folder: 'C:/Apache24\conf'