name: ADF Release pipeline

on: 
  push:
    branches:
    - pwsh-test

  
jobs:
  Deploy-ADF-Dev:
    runs-on: Windows
    environment: prod

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Copy Files
      run: |
          function Get-DestinationNetworkPath(
              [string]$targetPath,
              [string]$machineShare
          )
          {
              if(-not $machineShare)
              {
                  return $targetPath
              }

              $targetSpecificPath = Replace-First $targetPath ":" '$'    
              return [io.path]::Combine($machineShare, $targetSpecificPath)    
          }   

          function Get-MachineShare(
              [string]$fqdn,
              [string]$targetPath
              )
          {
              if([bool]([uri]$targetPath).IsUnc)
              {
                  return $targetPath
              }
              if($fqdn)
              {
                  return [IO.Path]::DirectorySeparatorChar + [IO.Path]::DirectorySeparatorChar + $fqdn
              }

              return ""
          }
          function Replace-First(
                [string]$text,
                [string]$search, 
                [string]$replace
                )
            {
                $pos = $text.IndexOf($search);
                if ($pos -le 0)
                {
                    return $text;
                }

                return $text.Substring(0, $pos) + $replace + $text.Substring($pos + $search.Length);
            }

          $secureAdminPassword = ConvertTo-SecureString ${{ vars.password }} -AsPlainText -Force
          $machineCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ${{ vars.ADMINLOGIN }}, $secureAdminPassword
          $machineShare = Get-MachineShare -fqdn ${{ vars.MACHINENAME }} -targetPath ${{ vars.DESTINATIONFOLDER }}    
          $destinationNetworkPath = Get-DestinationNetworkPath -targetPath ${{ vars.DESTINATIONFOLDER }} -machineShare $machineShare
          Write-Host "Destination $destinationNetworkPath"
          New-PSDrive -Name "WFCPSDrive" -PSProvider FileSystem -Root $destinationNetworkPath  -credential $machineCredential
          robocopy $SOURCE_DIRECTORY $destinationNetworkPath "" ; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          Remove-PSDrive -Name 'WFCPSDrive' -Force