name: ADF Release pipeline

on: 
  push:
    branches:
    - pwsh-test

  
jobs:
  Deploy-ADF-Dev:
    runs-on: Windows

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Copy Files
      run: |
          $User = "userdev"
          $PWord = ConvertTo-SecureString -String "P@ssw0rd1234" -AsPlainText -Force
          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
          $dst = "\\devcomp01\C$\Scripts\Portfolio"
          New-PSDrive -Name "WFCPSDrive" -PSProvider FileSystem -Root $dst  -credential $Credential
          $src = 'pwsh'
          try {
              robocopy $src $dst /E

              # Check the exit code
              if ($LASTEXITCODE -eq 0) {
                  Write-Host "Robocopy completed successfully."
              } elseif ($LASTEXITCODE -eq 1) {
                  Write-Host "Robocopy completed with some warnings or errors."
              } elseif ($LASTEXITCODE -eq 5) {
                  Write-Host "Robocopy encountered a severe error."
              } else {
                  Write-Host "Robocopy finished with exit code: $LASTEXITCODE"
              }
          }
          catch {
              # Handle any exceptions
              Write-Error "An error occurred during the robocopy process: $_"
          }