name: SQL Build & Release
on:
  push:
    branches:
      - sql-proj

run-name: SQL Build & Release-${{ github.run_number }}

permissions:
  id-token: write
  contents: read
  
jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - run: dotnet tool install -g microsoft.sqlpackage
    
    - run: sqlpackage /Action:Script /SourceFile:"Customer/Customer.dacpac" /TargetServerName:"rahul-sql-001.database.windows.net" /TargetDatabaseName:"Customer" /TargetUser:"sqladmin" /TargetPassword:"T#7vP2kY!mQz@9Lw"    /OutputPath:"customerUpdate.sql" /p:BlockOnPossibleDataLoss=False /p:IncludeTransactionalScripts=true
    
    - run: ls
    - run: cat customerUpdate.sql
    # - name: Build Customer
    #   run: |
    #     msbuild Customer/Customer.sqlproj /p:Configuration=Release

    
    # - name: Build Sales
    #   run: |
    #     msbuild Sales/Sales.sqlproj  /p:Configuration=Release


    # - name: Build 
    #   uses: actions/upload-artifact@v4
    #   with:
    #       name: customer-build-${{ github.run_number }}
    #       path: |
    #         Customer/bin

    # - name: Build 
    #   uses: actions/upload-artifact@v4
    #   with:
    #       name: sales-build-${{ github.run_number }}
    #       path: |
    #         Sales/bin
    

  # DEV:
  #   runs-on: windows-latest
  #   # needs: [Build]
  #   steps:
  #   # - name: Download Artifact
  #   #   uses: actions/download-artifact@v4

  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: 8.0.x

  #   - run: dotnet tool install -g microsoft.sqlpackage
 